name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Install
        run: cmake --install build --prefix install

      - name: Test FetchContent integration
        run: |
          cmake -E make_directory test_project
          cd test_project
          cat <<EOF > CMakeLists.txt
          cmake_minimum_required(VERSION 4.1.0)
          project(test_cnmea LANGUAGES CXX)
          include(FetchContent)
          FetchContent_Declare(
            cnmea
            GIT_REPOSITORY https://github.com/${{ github.repository }}.git
            GIT_TAG ${{ github.sha }}
          )
          FetchContent_MakeAvailable(cnmea)
          add_executable(test main.cpp)
          target_link_libraries(test PRIVATE cnmea)
          EOF
          echo '#include <cnmea/foo.hpp>\nint main() { return 0; }' > main.cpp
          cmake -B build -S .
          cmake --build build
